services:
  pgdatabase:
    image: postgres:13
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes: 
      - "c:/Projects/nyc_taxi/docker/nyc_taxi_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

# Here, there will be 2 containers running, pgdatabase and pgadmin.
# They will automatically be put on the same network.
# They can access each other using their service names (pgdatabase and pgadmin).
# Run in the terminal: docker-compose up -d
  # (must be in same directory as this docker-compose.yml file).
# To stop the containers, run: docker-compose down
